version = 1
auto_approve_usernames = ["dependabot", "yowainwright"]
merge.automerge_label = ['dependencies', 'automerge ğŸš€', "codependencies"]
update.autoupdate_labels = ['dependencies','autoupdate ğŸ”']
